import os
import secrets
import string

def generate_password(length=16):
    """Generate a secure random password"""
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))

def main():
    print("=" * 60)
    print("   Django Server Config Generator - Production Ready")
    print("=" * 60)
    print()
    
    # Inputs
    app_name = input("App Name (e.g., river): ").strip().lower()
    domain = input("Domain (e.g., market.plot.org.za): ").strip().lower()
    proj_folder = input("Django Project Folder (where settings.py is, e.g., river): ").strip()
    email = input("Admin Email (for SSL certificate): ").strip()
    has_celery = input("Enable Celery? (y/n): ").lower() == 'y'
    
    redis_db = "0"
    if has_celery:
        redis_db = input("Redis DB Number (0=Default, 1=Market, 2+=Other): ").strip()

    # Derived Variables
    base_path = f"/home/carbonplanner/apps/{app_name}"
    db_pass = generate_password()
    secret_key = generate_password(50)

    # Create local directory
    if not os.path.exists(app_name):
        os.makedirs(app_name)
        print(f"✓ Created directory: {app_name}/")

    # 1. PSQL COMMANDS
    psql_content = f"""-- PostgreSQL Setup for {app_name}
-- Run these commands on your PostgreSQL server

-- 1. Create DB and User
CREATE DATABASE {app_name}_db;
CREATE USER {app_name}_user WITH PASSWORD '{db_pass}';
GRANT ALL PRIVILEGES ON DATABASE {app_name}_db TO {app_name}_user;

-- 2. Connect to the new database (CRITICAL STEP)
\\c {app_name}_db

-- 3. Grant schema permissions
GRANT ALL ON SCHEMA public TO {app_name}_user;
ALTER DATABASE {app_name}_db OWNER TO {app_name}_user;

-- 4. Exit
\\q
"""

    # 2. .ENV FILE
    env_content = f"""# Production Environment Configuration
# Generated by config_gen.py

# Django Settings
DEBUG=False
SECRET_KEY={secret_key}
ALLOWED_HOSTS={domain},localhost,127.0.0.1

# Database Configuration (PostgreSQL)
DB_NAME={app_name}_db
DB_USER={app_name}_user
DB_PASSWORD={db_pass}
DB_HOST=localhost
DB_PORT=5432

# Media Files Storage
# For production, configure one of these:
# Option 1: Local filesystem (Nginx will serve)
MEDIA_ROOT={base_path}/media
# Option 2: AWS S3 (uncomment and configure)
# AWS_ACCESS_KEY_ID=your-access-key
# AWS_SECRET_ACCESS_KEY=your-secret-key
# AWS_STORAGE_BUCKET_NAME=your-bucket-name
# DEFAULT_FILE_STORAGE=storages.backends.s3boto3.S3Boto3Storage

# Static Files
STATIC_ROOT={base_path}/staticfiles

# Email Settings (optional)
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER=your-email@example.com
# EMAIL_HOST_PASSWORD=your-app-password

# Timezone & Language
TIME_ZONE=Africa/Johannesburg
LANGUAGE_CODE=en-us
"""
    if has_celery:
        env_content += f"""
# Celery Configuration
CELERY_BROKER_URL=redis://localhost:6379/{redis_db}
CELERY_RESULT_BACKEND=redis://localhost:6379/{redis_db}
"""

    # 3. GUNICORN SERVICE (Production Ready)
    web_service = f"""[Unit]
Description=Gunicorn for {app_name}
After=network.target

[Service]
User=carbonplanner
Group=www-data
WorkingDirectory={base_path}

# Load environment variables from .env file
EnvironmentFile={base_path}/.env

# Create directories if they don't exist
ExecStartPre=/bin/mkdir -p {base_path}/media
ExecStartPre=/bin/chown -R carbonplanner:www-data {base_path}/media
ExecStartPre=/bin/mkdir -p /var/log/gunicorn
ExecStartPre=/bin/chown -R carbonplanner:www-data /var/log/gunicorn

# Gunicorn process with optimized settings
ExecStart={base_path}/venv/bin/gunicorn \\
    --workers 3 \\
    --bind unix:{base_path}/{app_name}.sock \\
    --access-logfile /var/log/gunicorn/{app_name}_access.log \\
    --error-logfile /var/log/gunicorn/{app_name}_error.log \\
    --capture-output \\
    --enable-stdio-inheritance \\
    --worker-class sync \\
    --worker-connections 1000 \\
    --max-requests 1000 \\
    --max-requests-jitter 50 \\
    --timeout 60 \\
    --keep-alive 2 \\
    {proj_folder}.wsgi:application

# Restart policy
Restart=on-failure
RestartSec=5s
StartLimitInterval=60s
StartLimitBurst=3

# Security
NoNewPrivileges=true
ProtectHome=false

[Install]
WantedBy=multi-user.target
"""

    # 4. CELERY SERVICE
    worker_service = ""
    if has_celery:
        worker_service = f"""[Unit]
Description=Celery Worker for {app_name}
After=network.target

[Service]
Type=simple
User=carbonplanner
Group=www-data
WorkingDirectory={base_path}
EnvironmentFile={base_path}/.env

ExecStart={base_path}/venv/bin/celery -A {proj_folder} worker --loglevel=info --concurrency=2
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
"""

    # 5. NGINX CONFIG (Production Ready with HTTPS)
    nginx_content = f"""# HTTP - Redirect to HTTPS
server {{
    listen 80;
    server_name {domain};
    
    # Certbot challenge location
    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
    }}
    
    # Redirect all HTTP to HTTPS
    location / {{
        return 301 https://$server_name$request_uri;
    }}
}}

# HTTPS - Main server block
server {{
    listen 443 ssl http2;
    server_name {domain};
    
    # SSL Configuration (Certbot handles this)
    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    
    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
    
    # Favicon
    location = /favicon.ico {{ 
        access_log off; 
        log_not_found off; 
    }}
    
    # Static files - Long-term caching
    location /static/ {{
        alias {base_path}/staticfiles/;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
        try_files $uri $uri/ =404;
    }}
    
    # Media files - Long-term caching
    location /media/ {{
        alias {base_path}/media/;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
        try_files $uri $uri/ =404;
    }}
    
    # Django application via Gunicorn
    location / {{
        include proxy_params;
        proxy_pass http://unix:{base_path}/{app_name}.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
    }}
    
    # Client max body size for file uploads (10MB)
    client_max_body_size 10M;
}}
"""

    # 6. DEPLOYMENT SCRIPT
    deploy_script = f"""#!/bin/bash
# {app_name} Deployment Script
# Run this on your production server

set -e  # Exit on any error

echo "=== {app_name} Production Deployment ==="

# Configuration
APP_NAME="{app_name}"
DOMAIN="{domain}"
APP_USER="carbonplanner"
APP_DIR="{base_path}"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "ERROR: This script must be run as root (use sudo)"
   exit 1
fi

echo "[1/8] Updating system packages..."
apt update && apt upgrade -y

echo "[2/8] Installing dependencies..."
apt install -y python3-pip python3-venv python3-dev nginx postgresql postgresql-contrib certbot python3-certbot-nginx

echo "[3/8] Creating log directories..."
mkdir -p /var/log/gunicorn
chown -R $APP_USER:$APP_USER /var/log/gunicorn

echo "[4/8] Setting up database..."
sudo -u postgres psql -f psql_setup.sql || echo "Database may already exist, continuing..."

echo "[5/8] Setting up Python environment..."
cd $APP_DIR
if [ ! -d "venv" ]; then
    sudo -u $APP_USER python3 -m venv venv
fi
sudo -u $APP_USER $APP_DIR/venv/bin/pip install --upgrade pip
sudo -u $APP_USER $APP_DIR/venv/bin/pip install -r requirements.txt || echo "Warning: requirements.txt not found"

echo "[6/8] Running Django setup..."
export $(grep -v '^#' .env | xargs)
sudo -u $APP_USER $APP_DIR/venv/bin/python manage.py migrate
sudo -u $APP_USER $APP_DIR/venv/bin/python manage.py collectstatic --noinput

echo "[7/8] Configuring services..."
cp {app_name}_web.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable {app_name}_web
cp nginx_config /etc/nginx/sites-available/{app_name}
ln -sf /etc/nginx/sites-available/{app_name} /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
nginx -t

echo "[8/8] Starting services and setting up SSL..."
systemctl restart {app_name}_web
systemctl restart nginx
certbot --nginx -d $DOMAIN --non-interactive --agree-tos --email {email} || echo "SSL setup may require manual configuration"

echo ""
echo "=== Deployment Complete! ==="
echo ""
echo "Your application should be available at:"
echo "  - https://{domain}"
echo ""
echo "Useful commands:"
echo "  - View logs: sudo journalctl -u {app_name}_web -f"
echo "  - Restart: sudo systemctl restart {app_name}_web"
echo "  - Status: sudo systemctl status {app_name}_web"
echo "  - Test config: sudo nginx -t"
"""

    # Write files
    files = {
        "psql_setup.sql": psql_content,
        ".env": env_content,
        f"{app_name}_web.service": web_service,
        "nginx_config": nginx_content,
        "deploy.sh": deploy_script,
    }
    if has_celery:
        files[f"{app_name}_worker.service"] = worker_service

    for filename, content in files.items():
        filepath = os.path.join(app_name, filename)
        with open(filepath, "w") as f:
            f.write(content)
        print(f"✓ Created: {app_name}/{filename}")

    print()
    print("=" * 60)
    print("   Configuration Files Generated Successfully!")
    print("=" * 60)
    print()
    print("Next Steps:")
    print("1. Review and customize files in the '{app_name}/' folder")
    print("2. Copy .env to your server at: {base_path}/.env")
    print("3. Run psql_setup.sql on your PostgreSQL server")
    print("4. Copy service files to /etc/systemd/system/")
    print("5. Copy nginx_config to /etc/nginx/sites-available/{app_name}")
    print("6. Run deploy.sh on your server (or follow manual steps)")
    print()
    print("SSL Certificate:")
    print("  After DNS is configured, run:")
    print("  sudo certbot --nginx -d {domain}")
    print()

if __name__ == "__main__":
    main()
