# Generated by Django 6.0.2 on 2026-02-16
from django.db import migrations

def add_real_world_task_templates(apps, schema_editor):
    TaskTemplate = apps.get_model('core', 'TaskTemplate')
    
    # Real-world task templates based on last year's activities
    real_world_templates = [
        {
            'name': 'Emergency Litter Cleanup',
            'task_type': 'litter_run',
            'default_instructions': 'Emergency cleanup after heavy rains or flooding. Focus on large debris, plastic waste, and hazardous materials. Use safety gear and coordinate with city waste removal if needed.',
        },
        {
            'name': 'River Bank Stabilization',
            'task_type': 'weeding',
            'default_instructions': 'Clear invasive species from river banks to prevent erosion. Plant erosion-control vegetation. Install erosion mats if necessary.',
        },
        {
            'name': 'Native Tree Planting',
            'task_type': 'planting',
            'default_instructions': 'Plant indigenous trees along river corridor. Species: Cape Ash, Wild Olive, River Indigo. Spacing: 5m apart. Water thoroughly and install tree guards.',
        },
        {
            'name': 'Water Quality Monitoring',
            'task_type': 'litter_run',
            'default_instructions': 'Collect water samples at designated points. Test for pH, turbidity, and contaminants. Record observations of algae blooms or pollution.',
        },
        {
            'name': 'Community Cleanup Day',
            'task_type': 'litter_run',
            'default_instructions': 'Organize community volunteers for river cleanup. Provide gloves, bags, and refreshments. Focus on public access areas and educational outreach.',
        },
        {
            'name': 'Invasive Plant Removal - Wattle',
            'task_type': 'weeding',
            'default_instructions': 'Targeted removal of Australian Wattle (Acacia species). Cut and treat stumps with herbicide. Bag seeds to prevent spread.',
        },
        {
            'name': 'Wetland Planting',
            'task_type': 'planting',
            'default_instructions': 'Plant wetland species in riparian zone. Species: Cyperus, Juncus, Phragmites. Plant in clusters for natural wetland regeneration.',
        },
        {
            'name': 'Debris Removal - Large Items',
            'task_type': 'litter_run',
            'default_instructions': 'Remove large debris: tires, furniture, construction waste. Coordinate with city for special waste collection. Document items for reporting.',
        },
        {
            'name': 'Pathway Maintenance',
            'task_type': 'weeding',
            'default_instructions': 'Clear overgrowth from public pathways. Trim vegetation for safe access. Report any pathway damage to city maintenance.',
        },
        {
            'name': 'Pollinator Garden Planting',
            'task_type': 'planting',
            'default_instructions': 'Create pollinator-friendly garden with indigenous flowering plants. Species: Agapanthus, Kniphofia, Watsonia. Plant in sunny locations.',
        },
        {
            'name': 'Storm Drain Clearing',
            'task_type': 'litter_run',
            'default_instructions': 'Clear litter and debris from storm drains and culverts. Ensure water flow is not obstructed. Report any structural damage.',
        },
        {
            'name': 'Biological Control Monitoring',
            'task_type': 'weeding',
            'default_instructions': 'Monitor effectiveness of biological control agents (insects) on invasive plants. Record observations and population levels.',
        },
        {
            'name': 'Riparian Buffer Planting',
            'task_type': 'planting',
            'default_instructions': 'Establish riparian buffer zone with layered planting: trees, shrubs, ground cover. Minimum 10m width from river edge.',
        },
        {
            'name': 'Illegal Dumping Site Cleanup',
            'task_type': 'litter_run',
            'default_instructions': 'Clean up identified illegal dumping sites. Document evidence for enforcement. Install warning signs if recurring problem.',
        },
        {
            'name': 'Seed Collection',
            'task_type': 'weeding',
            'default_instructions': 'Collect seeds from healthy indigenous plants for propagation. Label with species, location, date. Store in cool, dry conditions.',
        },
        {
            'name': 'Educational Planting Day',
            'task_type': 'planting',
            'default_instructions': 'Planting event with school groups or community organizations. Focus on education about river ecology. Provide planting demonstrations.',
        },
    ]
    
    for template_data in real_world_templates:
        TaskTemplate.objects.create(**template_data)

def remove_real_world_task_templates(apps, schema_editor):
    TaskTemplate = apps.get_model('core', 'TaskTemplate')
    # Remove templates added by this migration (excluding the original 3)
    template_names = [
        'Emergency Litter Cleanup',
        'River Bank Stabilization',
        'Native Tree Planting',
        'Water Quality Monitoring',
        'Community Cleanup Day',
        'Invasive Plant Removal - Wattle',
        'Wetland Planting',
        'Debris Removal - Large Items',
        'Pathway Maintenance',
        'Pollinator Garden Planting',
        'Storm Drain Clearing',
        'Biological Control Monitoring',
        'Riparian Buffer Planting',
        'Illegal Dumping Site Cleanup',
        'Seed Collection',
        'Educational Planting Day',
    ]
    TaskTemplate.objects.filter(name__in=template_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_real_world_task_templates, remove_real_world_task_templates),
    ]
