# Generated by Django 6.0.2 on 2026-02-16
from django.db import migrations

def add_example_sections(apps, schema_editor):
    Section = apps.get_model('core', 'Section')
    
    # Example sections based on the implementation document
    example_sections = [
        {
            'name': 'Mowbray',
            'color_code': '#FF6B6B',  # Red
            'current_stage': 'clearing',
            'description': 'Mowbray section of the Liesbeek River. Known for invasive plant issues and regular litter accumulation.',
        },
        {
            'name': 'San Souci',
            'color_code': '#4ECDC4',  # Teal
            'current_stage': 'planting',
            'description': 'San Souci wetland area. Focus on wetland restoration and water quality improvement.',
        },
        {
            'name': 'Upper Liesbeek',
            'color_code': '#45B7D1',  # Blue
            'current_stage': 'mitigation',
            'description': 'Upper reaches of the Liesbeek River. Source protection and erosion control priority.',
        },
        {
            'name': 'Observatory',
            'color_code': '#96CEB4',  # Green
            'current_stage': 'follow_up',
            'description': 'Observatory section with community gardens and public access points.',
        },
        {
            'name': 'Rondebosch Common',
            'color_code': '#FFEAA7',  # Yellow
            'current_stage': 'community',
            'description': 'Rondebosch Common area. Community engagement and educational activities focus.',
        },
        {
            'name': 'Lower Liesbeek',
            'color_code': '#DDA0DD',  # Plum
            'current_stage': 'clearing',
            'description': 'Lower section near river mouth. Tidal influence and sedimentation issues.',
        },
        {
            'name': 'UCT Grounds',
            'color_code': '#98D8C8',  # Mint
            'current_stage': 'planting',
            'description': 'University of Cape Town campus section. Collaboration with UCT environmental programs.',
        },
        {
            'name': 'Black River Confluence',
            'color_code': '#F7DC6F',  # Gold
            'current_stage': 'mitigation',
            'description': 'Confluence with Black River. Water quality monitoring and pollution control focus.',
        },
    ]
    
    for section_data in example_sections:
        Section.objects.create(**section_data)

def remove_example_sections(apps, schema_editor):
    Section = apps.get_model('core', 'Section')
    section_names = [
        'Mowbray',
        'San Souci', 
        'Upper Liesbeek',
        'Observatory',
        'Rondebosch Common',
        'Lower Liesbeek',
        'UCT Grounds',
        'Black River Confluence',
    ]
    Section.objects.filter(name__in=section_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_real_world_task_templates'),
    ]

    operations = [
        migrations.RunPython(add_example_sections, remove_example_sections),
    ]
