# Generated by Django 6.0.2 on 2026-02-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_example_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Order of the section (upstream to downstream)'),
        ),
    ]
