# Generated by Django 6.0.2 on 2026-02-17
from django.db import migrations, models


def update_tasks_and_sections(apps, schema_editor):
    """
    Update task templates and sections based on client feedback.
    
    Tasks are split into:
    - Team tasks: Field work activities (original tasks)
    - Manager tasks: Administrative activities (new tasks)
    
    Sections are ordered upstream to downstream along the river.
    """
    TaskTemplate = apps.get_model('core', 'TaskTemplate')
    Section = apps.get_model('core', 'Section')
    
    # Clear existing task templates
    TaskTemplate.objects.all().delete()
    
    # Team tasks - field work activities
    team_tasks = [
        {
            'name': 'Emergency Litter Cleanup',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Emergency cleanup after heavy rains or flooding. Focus on large debris, plastic waste, and hazardous materials. Use safety gear and coordinate with city waste removal if needed.',
        },
        {
            'name': 'River Bank Stabilization',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Clear invasive species from river banks to prevent erosion. Plant erosion-control vegetation. Install erosion mats if necessary.',
        },
        {
            'name': 'Native Tree Planting',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Plant indigenous trees along river corridor. Species: Cape Ash, Wild Olive, River Indigo. Spacing: 5m apart. Water thoroughly and install tree guards.',
        },
        {
            'name': 'Water Quality Monitoring',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Collect water samples at designated points. Test for pH, turbidity, and contaminants. Record observations of algae blooms or pollution.',
        },
        {
            'name': 'Community Cleanup Day',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Organize community volunteers for river cleanup. Provide gloves, bags, and refreshments. Focus on public access areas and educational outreach.',
        },
        {
            'name': 'Invasive Plant Removal - Wattle',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Targeted removal of Australian Wattle (Acacia species). Cut and treat stumps with herbicide. Bag seeds to prevent spread.',
        },
        {
            'name': 'Wetland Planting',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Plant wetland species in riparian zone. Species: Cyperus, Juncus, Phragmites. Plant in clusters for natural wetland regeneration.',
        },
        {
            'name': 'Debris Removal - Large Items',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Remove large debris: tires, furniture, construction waste. Coordinate with city for special waste collection. Document items for reporting.',
        },
        {
            'name': 'Pathway Maintenance',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Clear overgrowth from public pathways. Trim vegetation for safe access. Report any pathway damage to city maintenance.',
        },
        {
            'name': 'Pollinator Garden Planting',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Create pollinator-friendly garden with indigenous flowering plants. Species: Agapanthus, Kniphofia, Watsonia. Plant in sunny locations.',
        },
        {
            'name': 'Storm Drain Clearing',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Clear litter and debris from storm drains and culverts. Ensure water flow is not obstructed. Report any structural damage.',
        },
        {
            'name': 'Biological Control Monitoring',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Monitor effectiveness of biological control agents (insects) on invasive plants. Record observations and population levels.',
        },
        {
            'name': 'Riparian Buffer Planting',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Establish riparian buffer zone with layered planting: trees, shrubs, ground cover. Minimum 10m width from river edge.',
        },
        {
            'name': 'Illegal Dumping Site Cleanup',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Clean up identified illegal dumping sites. Document evidence for enforcement. Install warning signs if recurring problem.',
        },
        {
            'name': 'Seed Collection',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Collect seeds from healthy indigenous plants for propagation. Label with species, location, date. Store in cool, dry conditions.',
        },
        {
            'name': 'Educational Planting Day',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Planting event with school groups or community organizations. Focus on education about river ecology. Provide planting demonstrations.',
        },
    ]
    
    # Manager tasks - administrative activities
    manager_tasks = [
        {
            'name': 'River survey',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Conduct survey of river section to assess conditions, document issues, and plan interventions.',
        },
        {
            'name': 'Meeting',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Attend scheduled meeting. Take notes and follow up on action items.',
        },
        {
            'name': 'Workshop',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Participate in workshop session. Prepare materials in advance and document outcomes.',
        },
        {
            'name': 'Reporting',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Complete required reports and documentation. Submit by deadline.',
        },
        {
            'name': 'Fundraising',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Engage in fundraising activities. Document donor interactions and follow up on pledges.',
        },
        {
            'name': 'Planning',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Participate in planning activities. Review schedules, allocate resources, and set priorities.',
        },
        {
            'name': 'Team admin',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Handle team administrative tasks including scheduling, communications, and resource coordination.',
        },
        {
            'name': 'Intern admin',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Manage intern-related administrative tasks including onboarding, scheduling, and evaluations.',
        },
        {
            'name': 'Committee admin',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Handle committee administrative duties including minutes, scheduling meetings, and tracking decisions.',
        },
        {
            'name': 'Media',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Manage media-related activities including press releases, social media, and public communications.',
        },
        {
            'name': 'Outreach',
            'task_type': 'litter_run',
            'assignee_type': 'manager',
            'default_instructions': 'Conduct community outreach activities. Build relationships with stakeholders and promote river conservation.',
        },
    ]
    
    # Create all tasks
    for task_data in team_tasks + manager_tasks:
        TaskTemplate.objects.create(**task_data)
    
    # Clear existing sections
    Section.objects.all().delete()
    
    # New sections ordered upstream to downstream
    new_sections = [
        {
            'name': 'Boschenheuwel Arboretum',
            'color_code': '#228B22',  # Forest Green
            'current_stage': 'mitigation',
            'description': 'Upstream starting point at Boschenheuwel Arboretum. Focus on source protection and indigenous vegetation.',
            'position': 1,
        },
        {
            'name': 'Riverside Road to ULRG',
            'color_code': '#4682B4',  # Steel Blue
            'current_stage': 'clearing',
            'description': 'Section from Riverside Road to Upper Liesbeek River Garden. Transition zone with mixed land use.',
            'position': 2,
        },
        {
            'name': 'Paradise Park',
            'color_code': '#32CD32',  # Lime Green
            'current_stage': 'planting',
            'description': 'Paradise Park section with established green spaces and recreational areas.',
            'position': 3,
        },
        {
            'name': 'San Souci',
            'color_code': '#4ECDC4',  # Teal
            'current_stage': 'planting',
            'description': 'San Souci wetland area. Focus on wetland restoration and water quality improvement.',
            'position': 4,
        },
        {
            'name': 'Newlands',
            'color_code': '#9370DB',  # Medium Purple
            'current_stage': 'follow_up',
            'description': 'Newlands section with residential and park areas. Community engagement focus.',
            'position': 5,
        },
        {
            'name': 'Rondebosch',
            'color_code': '#FFD700',  # Gold
            'current_stage': 'community',
            'description': 'Rondebosch area with schools and community institutions. Educational activities focus.',
            'position': 6,
        },
        {
            'name': 'Rosebank',
            'color_code': '#FF6347',  # Tomato
            'current_stage': 'clearing',
            'description': 'Rosebank section with mixed urban development. Invasive species management priority.',
            'position': 7,
        },
        {
            'name': 'Mowbray',
            'color_code': '#FF6B6B',  # Red
            'current_stage': 'clearing',
            'description': 'Mowbray section of the Liesbeek River. Known for invasive plant issues and regular litter accumulation.',
            'position': 8,
        },
        {
            'name': 'Observatory',
            'color_code': '#96CEB4',  # Green
            'current_stage': 'follow_up',
            'description': 'Observatory section with community gardens and public access points. Downstream endpoint.',
            'position': 9,
        },
    ]
    
    for section_data in new_sections:
        Section.objects.create(**section_data)


def revert_tasks_and_sections(apps, schema_editor):
    """
    Revert to empty state - data will need to be re-populated manually.
    """
    TaskTemplate = apps.get_model('core', 'TaskTemplate')
    Section = apps.get_model('core', 'Section')
    
    TaskTemplate.objects.all().delete()
    Section.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='assignee_type',
            field=models.CharField(choices=[('team', 'Team'), ('manager', 'Manager')], default='team', max_length=10),
        ),
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'ordering': ['assignee_type', 'name']},
        ),
        migrations.RunPython(update_tasks_and_sections, revert_tasks_and_sections),
    ]
