# Generated by Django 6.0.2 on 2026-02-17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_tasks_and_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='assignee_type',
            field=models.CharField(choices=[('team', 'Team'), ('manager', 'Manager')], default='team', max_length=10),
        ),
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'ordering': ['assignee_type', 'name']},
        ),
    ]
