# Generated by Django 6.0.2 on 2026-02-17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_tasks_and_sections'),
    ]

    operations = [
        # Note: assignee_type field already added in migration 0006
        # Keeping only model options update for migration history consistency
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'ordering': ['assignee_type', 'name']},
        ),
    ]
