# Generated by Django 6.0.2 on 2026-02-17
from django.db import migrations


def update_task_assignee_types(apps, schema_editor):
    """
    Update existing task templates to have correct assignee_type.
    Note: Migration 0006 already sets assignee_type correctly.
    This function is kept for migration history consistency.
    """
    pass


def revert_task_assignee_types(apps, schema_editor):
    """Revert all tasks to team type.
    Note: Migration 0006's revert function already handles reversion.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_tasktemplate_assignee_type'),
    ]

    operations = [
        migrations.RunPython(update_task_assignee_types, revert_task_assignee_types),
    ]
