# Generated by Django 6.0.2 on 2026-02-17
from django.db import migrations


def update_task_assignee_types(apps, schema_editor):
    """
    Update existing task templates to have correct assignee_type.
    Team tasks: Field work activities
    Manager tasks: Administrative activities
    """
    TaskTemplate = apps.get_model('core', 'TaskTemplate')
    
    # Manager task names (admin activities)
    manager_task_names = [
        'River survey',
        'Meeting',
        'Workshop',
        'Reporting',
        'Fundraising',
        'Planning',
        'Team admin',
        'Intern admin',
        'Committee admin',
        'Media',
        'Outreach',
    ]
    
    # Set manager tasks
    TaskTemplate.objects.filter(name__in=manager_task_names).update(assignee_type='manager')
    
    # Set all others as team tasks (field work)
    TaskTemplate.objects.exclude(name__in=manager_task_names).update(assignee_type='team')


def revert_task_assignee_types(apps, schema_editor):
    """Revert all tasks to team type."""
    TaskTemplate = apps.get_model('core', 'TaskTemplate')
    TaskTemplate.objects.all().update(assignee_type='team')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_tasktemplate_assignee_type'),
    ]

    operations = [
        migrations.RunPython(update_task_assignee_types, revert_task_assignee_types),
    ]
