# Generated by Django 6.0.2 on 2026-02-17
from django.db import migrations


def fix_tasks_and_types(apps, schema_editor):
    """
    Fix task templates:
    1. Update manager tasks to have task_type='admin' instead of 'litter_run'
    2. Add missing team tasks (15 additional tasks)
    """
    TaskTemplate = apps.get_model('core', 'TaskTemplate')
    
    # Manager tasks to update - these should have task_type='admin'
    manager_tasks_to_update = [
        'River survey',
        'Meeting',
        'Workshop',
        'Reporting',
        'Fundraising',
        'Planning',
        'Team admin',
        'Intern admin',
        'Committee admin',
        'Media',
        'Outreach',
    ]
    
    # Update manager tasks to admin type
    TaskTemplate.objects.filter(name__in=manager_tasks_to_update).update(task_type='admin')
    
    # Team tasks to create (additional 15 tasks)
    team_tasks_to_create = [
        {
            'name': 'Emergency Litter Cleanup',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Emergency cleanup after heavy rains or flooding. Focus on large debris, plastic waste, and hazardous materials. Use safety gear and coordinate with city waste removal if needed.',
        },
        {
            'name': 'River Bank Stabilization',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Clear invasive species from river banks to prevent erosion. Plant erosion-control vegetation. Install erosion mats if necessary.',
        },
        {
            'name': 'Native Tree Planting',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Plant indigenous trees along river corridor. Species: Cape Ash, Wild Olive, River Indigo. Spacing: 5m apart. Water thoroughly and install tree guards.',
        },
        {
            'name': 'Community Cleanup Day',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Organize community volunteers for river cleanup. Provide gloves, bags, and refreshments. Focus on public access areas and educational outreach.',
        },
        {
            'name': 'Invasive Plant Removal - Wattle',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Targeted removal of Australian Wattle (Acacia species). Cut and treat stumps with herbicide. Bag seeds to prevent spread.',
        },
        {
            'name': 'Wetland Planting',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Plant wetland species in riparian zone. Species: Cyperus, Juncus, Phragmites. Plant in clusters for natural wetland regeneration.',
        },
        {
            'name': 'Debris Removal - Large Items',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Remove large debris: tires, furniture, construction waste. Coordinate with city for special waste collection. Document items for reporting.',
        },
        {
            'name': 'Pathway Maintenance',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Clear overgrowth from public pathways. Trim vegetation for safe access. Report any pathway damage to city maintenance.',
        },
        {
            'name': 'Pollinator Garden Planting',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Create pollinator-friendly garden with indigenous flowering plants. Species: Agapanthus, Kniphofia, Watsonia. Plant in sunny locations.',
        },
        {
            'name': 'Storm Drain Clearing',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Clear litter and debris from storm drains and culverts. Ensure water flow is not obstructed. Report any structural damage.',
        },
        {
            'name': 'Biological Control Monitoring',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Monitor effectiveness of biological control agents (insects) on invasive plants. Record observations and population levels.',
        },
        {
            'name': 'Riparian Buffer Planting',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Establish riparian buffer zone with layered planting: trees, shrubs, ground cover. Minimum 10m width from river edge.',
        },
        {
            'name': 'Illegal Dumping Site Cleanup',
            'task_type': 'litter_run',
            'assignee_type': 'team',
            'default_instructions': 'Clean up identified illegal dumping sites. Document evidence for enforcement. Install warning signs if recurring problem.',
        },
        {
            'name': 'Seed Collection',
            'task_type': 'weeding',
            'assignee_type': 'team',
            'default_instructions': 'Collect seeds from healthy indigenous plants for propagation. Label with species, location, date. Store in cool, dry conditions.',
        },
        {
            'name': 'Educational Planting Day',
            'task_type': 'planting',
            'assignee_type': 'team',
            'default_instructions': 'Planting event with school groups or community organizations. Focus on education about river ecology. Provide planting demonstrations.',
        },
    ]
    
    # Create missing team tasks (skip if already exists)
    for task_data in team_tasks_to_create:
        if not TaskTemplate.objects.filter(name=task_data['name']).exists():
            TaskTemplate.objects.create(**task_data)


def revert_fixes(apps, schema_editor):
    """
    Revert changes: 
    1. Set manager tasks back to litter_run (though we don't know original state)
    2. Remove the 15 additional team tasks we added
    """
    TaskTemplate = apps.get_model('core', 'TaskTemplate')
    
    # Set manager tasks back to litter_run (approximation)
    manager_tasks_to_revert = [
        'River survey',
        'Meeting',
        'Workshop',
        'Reporting',
        'Fundraising',
        'Planning',
        'Team admin',
        'Intern admin',
        'Committee admin',
        'Media',
        'Outreach',
    ]
    TaskTemplate.objects.filter(name__in=manager_tasks_to_revert).update(task_type='litter_run')
    
    # Remove the 15 additional team tasks we added
    additional_team_tasks = [
        'Emergency Litter Cleanup',
        'River Bank Stabilization',
        'Native Tree Planting',
        'Community Cleanup Day',
        'Invasive Plant Removal - Wattle',
        'Wetland Planting',
        'Debris Removal - Large Items',
        'Pathway Maintenance',
        'Pollinator Garden Planting',
        'Storm Drain Clearing',
        'Biological Control Monitoring',
        'Riparian Buffer Planting',
        'Illegal Dumping Site Cleanup',
        'Seed Collection',
        'Educational Planting Day',
    ]
    TaskTemplate.objects.filter(name__in=additional_team_tasks).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_admin_task_type'),
    ]

    operations = [
        migrations.RunPython(fix_tasks_and_types, revert_fixes),
    ]
