# Generated by Django 6.0.2 on 2026-02-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_task_assignee_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='task_type',
            field=models.CharField(choices=[('litter_run', 'Litter Run'), ('weeding', 'Weeding'), ('planting', 'Planting'), ('admin', 'Admin')], max_length=20),
        ),
    ]
