# Generated by Django 6.0.2 on 2026-02-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_tasks_and_types'),
        ('core', '0011_fix_assignee_type_schema'),
    ]

    operations = [
    ]
