# Generated by Django 6.0.2 on 2026-02-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260217_1414'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_date_08586d_idx',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['date'], name='core_task_date_6d746c_idx'),
        ),
    ]
