# Generated by Django 6.0.2 on 2026-02-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_task_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive templates are hidden from task creation but preserved for existing tasks'),
        ),
    ]
