# Generated by Django 6.0.2 on 2026-02-18 11:35

import django.db.models.deletion
from django.db import migrations, models


def create_initial_stage_history(apps, schema_editor):
    """Create initial stage history entries for existing sections."""
    Section = apps.get_model('core', 'Section')
    SectionStageHistory = apps.get_model('core', 'SectionStageHistory')
    
    for section in Section.objects.all():
        SectionStageHistory.objects.create(
            section=section,
            stage=section.current_stage,
            changed_at=section.created_at
        )


def reverse_initial_stage_history(apps, schema_editor):
    """Remove all initial stage history entries."""
    SectionStageHistory = apps.get_model('core', 'SectionStageHistory')
    SectionStageHistory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_tasktemplate_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('mitigation', 'Mitigation'), ('clearing', 'Clearing'), ('planting', 'Planting'), ('follow_up', 'Follow-up'), ('community', 'Community')], max_length=20)),
                ('changed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='core.section')),
            ],
            options={
                'verbose_name': 'Stage History',
                'verbose_name_plural': 'Stage History',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['section', 'changed_at'], name='core_sectio_section_98be4d_idx')],
            },
        ),
        migrations.RunPython(create_initial_stage_history, reverse_initial_stage_history),
    ]
