# Generated by Django 6.0.2 on 2026-02-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sectionstagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='metric_type',
            field=models.CharField(choices=[('litter_general', 'Litter (General)'), ('litter_recyclable', 'Litter (Recyclable)'), ('plant', 'Plant'), ('weed', 'Weeding / Removal')], max_length=20),
        ),
    ]
