# Generated by Django 6.0.2 on 2026-02-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_metric_metric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='boundary_data',
            field=models.JSONField(blank=True, default=dict, help_text='GeoJSON-style polygon coordinates for section boundaries'),
        ),
        migrations.AddField(
            model_name='section',
            name='center_point',
            field=models.JSONField(blank=True, default=dict, help_text='GeoJSON-style center point coordinates [lng, lat]'),
        ),
    ]
