# Generated by Django 6.0.2 on 2026-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_section_boundary_data_section_center_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='status',
            field=models.CharField(choices=[('priority', 'Priority'), ('low_priority', 'Low Priority')], default='priority', help_text='Priority level for this section', max_length=20),
        ),
    ]
