# Generated by Django 6.0.2 on 2026-02-20 07:05

import django.db.models.deletion
from django.db import migrations, models


def create_statuses_and_migrate_data(apps, schema_editor):
    Status = apps.get_model('core', 'Status')
    Section = apps.get_model('core', 'Section')
    
    # Create all statuses with their mappings
    status_map = {
        'priority': Status.objects.create(name='Priority', color_code='#FF0000', position=1, is_active=True),
        'low_priority': Status.objects.create(name='Low Priority', color_code='#FFA500', position=2, is_active=True),
    }
    
    # Create additional statuses
    additional_statuses = [
        ('Active care', '#00AA00', 3),
        ('Stable', '#0066CC', 4),
        ('Maintenance', '#9933CC', 5),
        ('Project', '#FF6600', 6),
    ]
    for name, color, position in additional_statuses:
        Status.objects.get_or_create(name=name, defaults={'color_code': color, 'position': position, 'is_active': True})
    
    # Migrate existing Section data
    for section in Section.objects.all():
        if section.status in status_map:
            section.status_fk = status_map[section.status]
            section.save(update_fields=['status_fk'])


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_section_status'),
    ]

    operations = [
        # Step 1: Create Status model
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_code', models.CharField(default='#808080', help_text='Hex color code for visual distinction', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Only active statuses are shown in dropdowns')),
                ('position', models.PositiveIntegerField(default=0, help_text='Order in which statuses appear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'ordering': ['position', 'name'],
            },
        ),
        # Step 2: Add a temporary field to hold the FK
        migrations.AddField(
            model_name='section',
            name='status_fk',
            field=models.ForeignKey(blank=True, help_text='Current status of this section', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status'),
        ),
        # Step 3: Create statuses and migrate data
        migrations.RunPython(create_statuses_and_migrate_data, reverse_migration),
        # Step 4: Remove old status field
        migrations.RemoveField(
            model_name='section',
            name='status',
        ),
        # Step 5: Rename the new field to status
        migrations.RenameField(
            model_name='section',
            old_name='status_fk',
            new_name='status',
        ),
    ]
