# Generated by Django 6.0.2 on 2026-03-12 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_migrate_task_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='section',
            field=models.ForeignKey(blank=True, help_text='River section where activity took place (optional for general logs)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.section'),
        ),
    ]
