# Generated by Django 6.0.2 on 2026-03-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_visitlog_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee_type',
            field=models.CharField(choices=[('team', 'Team'), ('manager', 'Manager'), ('chairperson', 'Chairperson')], default='team', max_length=15),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='assignee_type',
            field=models.CharField(choices=[('team', 'Team'), ('manager', 'Manager'), ('chairperson', 'Chairperson')], default='team', max_length=15),
        ),
    ]
