# Generated by Django 6.0.2 on 2026-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_task_assignee_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='applicable_to',
            field=models.CharField(choices=[('team', 'Team'), ('manager', 'Manager'), ('chairperson', 'Chairperson'), ('all', 'All')], default='all', help_text='Which assignee types this task type is applicable to', max_length=15),
        ),
    ]
