# Generated by Django 6.0.2 on 2026-03-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_tasktype_applicable_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Links tasks created as a series', null=True),
        ),
    ]
