# Generated by Django 6.0.2 on 2026-03-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_task_group_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date', 'todo_position']},
        ),
        migrations.AddField(
            model_name='task',
            name='is_rolling',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='todo_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='todo_status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('done', 'Done')], db_index=True, default='todo', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_rolling'], name='core_task_is_roll_fe2f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['todo_status'], name='core_task_todo_st_5f0c7b_idx'),
        ),
    ]
