# Generated by Django 6.0.2 on 2026-03-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_task_options_task_is_rolling_task_is_urgent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='color_class',
            field=models.CharField(default='bg-slate-50 text-slate-600 border-slate-100', help_text="Tailwind CSS classes for styling (e.g., 'bg-amber-50 text-amber-600 border-amber-100')", max_length=150),
        ),
    ]
