# Generated by Django 6.0.2 on 2026-03-19 11:51

from django.db import migrations


def fix_applicable_to_data(apps, schema_editor):
    """Fix TaskType applicable_to values from old 'both' to new 'all'."""
    TaskType = apps.get_model('core', 'TaskType')
    # Update task types with old 'both' value to new 'all' value
    TaskType.objects.filter(applicable_to='both').update(applicable_to='all')


def revert_applicable_to_data(apps, schema_editor):
    """Revert TaskType applicable_to values from 'all' back to 'both'."""
    TaskType = apps.get_model('core', 'TaskType')
    # Revert task types with 'all' value back to 'both'
    TaskType.objects.filter(applicable_to='all').update(applicable_to='both')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_tasktype_color_class_length'),
    ]

    operations = [
        migrations.RunPython(fix_applicable_to_data, revert_applicable_to_data),
    ]
