# Generated by Django 6.0.2 on 2026-08-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_restore_template_task_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='participant_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
