# Generated by Django 6.0.2 on 2026-08-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_visitlog_participant_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='participant_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
